# Port
server.port=9000

# Update
spring.jpa.hibernate.ddl-auto=update

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5434/airbnb
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Dev Auth
airbnb.jwt.secret=3ffb5064704f3949ce6aa5e7e811d0e5eccd53e45785ebd86576ef0e1cdb1c95
airbnb.jwt.access-token.expiration=15m
airbnb.jwt.refresh-token.expiration=7d

airbnb.mail.enabled=true
spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.username=blps-airbnb@mail.ru
spring.mail.password=pETAiMpiwwqlRXL5Q3A6
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
airbnb.mail.from=blps-airbnb@mail.ru
