package org.mryrt.airbnb.auth.model;

public enum Permission {
    ALL_USER_READ,
    ALL_USER_UPDATE,
    ALL_USER_DELETE,

    LISTING_READ,
    LISTING_CREATE,
    LISTING_UPDATE,
    LISTING_DELETE,
    ALL_LISTING_READ,
    ALL_LISTING_UPDATE,
    ALL_LISTING_DELETE,

    BOOKING_READ,
    BOOKING_CREATE,
    BOOKING_DECIDE,
    ALL_BOOKING_READ,
    ALL_BOOKING_UPDATE,

    RESOLUTION_READ,
    RESOLUTION_REQUEST_MONEY,
    RESOLUTION_RESPOND,
    RESOLUTION_ESCALATE,
    RESOLUTION_COMPLAINT,
    ALL_RESOLUTION_READ,
    ALL_RESOLUTION_UPDATE,

    NOTIFICATION_READ,
    ALL_NOTIFICATION_READ,
}
